### ISSUE TITLE
Handling conversion of fields to @timestamp

### ISSUE THREAD

**Issue by tonymeehan** [elastic/ecs-mapper#14]
You can find a reference to an earlier discussion on this topic here: https://github.com/elastic/ecs-mapper/issues/3.

In thinking about this some more, I think we should implement a two changes for handling timestamp conversion.

1. A to_timestamp conversion will need to specify a format. We could use a default when no format is provided, probably UNIX_MS. But otherwise we'll need a ```format``` column. We shouldn't guess the timestamp format.

2. I'd like to treat the ```@timestamp``` as a special field and by default convert it to UNIX_MS unless 1) the user specifies the conversion format in the CSV or 2) the user specifies a different format on the command line, like --timestamp_format is one of: ISO8601, UNIX, UNIX_MS, or TAI64N from https://www.elastic.co/guide/en/elasticsearch/reference/master/date-processor.html.

Curious what you think @webmat.

**Comment by tonymeehan** [comment]
An alternative to #1 above is we stick with the existing [ACCEPTED_FORMAT_ACTIONS](https://github.com/elastic/ecs-mapper/blob/master/lib/mapping_loader.rb#L5) and add ```to_timestamp_unix_ms```, ```to_timestamp_unix```, ```to_timestamp_iso8601```, and ```to_timestamp_tai64n```. This would remove the need for a separate column to indicate the format.

We could do this and keep #2 to indicate the default conversion for ```@timestamp``` if none of the above is specified in the ```format_action``` column.

**Comment by webmat** [comment]
We cannot guess the timestamp format indeed. This tool never sees the events themselves; it only reads a CSV and outputs 3 pipelines :-)

I would like this tool to be driven by the CSV as much as possible. I don't object to CLI flags adjusting the behaviour a bit, but I want to make sure it's possible to do everything only via the CSV.

The way I think of it is this: assume we want to create & publish an "ecs-mappings" repo for users to share their mappings. When someone shares a mapping, they should be able to share a CSV that fully describes how this maps. I wouldn't want users to have to share "here's a CSV, and make sure to use X command line flag too" :-)

That said, anything we do here will have to work in Beats, Logstash and Elasticsearch. Let's figure out what we can describe from there, that can yield equivalent processors / filters for all 3 targets.

**Comment by webmat** [comment]
I doubt all 3 will support the same shorthands, for instance.

If they don't, perhaps our only option is to support a format string. Even then, we'll have to make sure the format string actually works in all 3 targets.

**Comment by tonymeehan** [comment]
I think we agree. Let me put up a draft PR this evening and let's work on this idea from that.

**Comment by webmat** [comment]
Before spending too much time on the code, I suggest surveying closely what's supported in all 3, and seeing if we can find some commonality :-)

**Comment by tonymeehan** [comment]
Good call.

- Ingest pipelines use the [date processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/date-processor.html) and support UNIX, UNIX_MS, ISO8601, and TAI64N
- FIlebeat uses the [timestamp processor](https://www.elastic.co/guide/en/beats/filebeat/current/processor-timestamp.html) and it supports UNIX and UNIX_MS.
- Logstash [date match filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html#plugins-filters-date-match) looks like it supports UNIX, UNIX_MS, ISO8601, and TAI64N.

I'm okay only supporting UNIX and UNIX_MS for now. If a user wants to use some other format, they can do what they do today with the ingest pipeline or logstash filter.

**Comment by webmat** [comment]
Ok, I think it makes sense.

Moreover, seeing that only one doesn't support ISO8601, I wonder if we can make up for it from ECS mapper?

Anyway, let's walk before we run :-) Let's go with unix ts for now and we can build on this later

**Comment by webmat** [comment]
I think we can close this, with #17 merged
