### ISSUE TITLE
It should be possible to apply format_actions in place (without a destination_field)

### ISSUE THREAD

**Issue by webmat** [elastic/ecs-mapper#16]
I think in #8 we lost the ability to apply a `format_action` to a `source_field` that's not moving to a different `destination_field`...

The `example/mapping.csv` deliberately had two lines like that, the source_fields were `successful` and `process.args`. See [this diff](https://github.com/elastic/ecs-mapper/pull/10/commits/76f4cb0fa42ca7f4962a47ab019025f9f6d4b2e8#diff-71c9e44ed7022de8ebf2d3e5fcd9a65c)

**Comment by tonymeehan** [comment]
Fixed by https://github.com/elastic/ecs-mapper/pull/17
