### ISSUE TITLE
Improve the naming of the copy/rename action taken on fields

### ISSUE THREAD

**Issue by webmat** [elastic/ecs-mapper#9]
The current state:

* The command line option is called `--rename-action` and defaults to "rename"
* The CSV column is called "rename" and defaults to the value of the flag `--rename-action` (which in turn defaults to "rename")

They're well aligned right now, but I'm not a fan of the naming, nor its defaults. Having a column named "rename" which can either contain "copy" or "rename" breaks my brain a little bit.

After #8, I think users will double down on having multiple rows for the same source field, to copy it in multiple places. The quintessential example is of course IP addresses being copied to the relevant `.address` field and its sister `.ip` fields, as well as copying them to both `source.` and `client.`.

The default action "rename" will not work well with this, of course. The generated pipelines will rename the source field the first time they see it, and the next line for the same source field will no longer have that source field present, and the pipeline will skip the action silently.

Therefore I propose changing the default action to "copy". This will ensure the getting started experience is as smooth as possible. Users who are sensitive to disk usage will still be able to override and do a rename on the last line, if they don't want to preserve the original field. Example:

| source_field | destination_field | copy_action |
| -- | -- | -- |
| SourceIP | source.ip |  |
| SourceIP | client.ip | rename |

To keep everything aligned, I propose the following:

- [ ] Rename the CLI option to `--copy-action`
  - Change the default to "copy" rather than "rename"
- [ ] Rename the expected column name to `copy_action` (still default to CLI option, which in turn now defaults to "copy")
- [ ] Adjust the documentation according to the new behaviour
  - considering the new defaults
  - add examples of processing the same source field to duplicate it, which is common in ECS

WDYT @tonymeehan @aleph-zero ?

**Comment by webmat** [comment]
Another thing we could do here (instead of, or in addition to) this proposed change, is detect whenever multiple lines are processing a given source_field.

When that happens, we could make sure to apply the changes described by each line (copy to all destination fields, applying their respective format_action), then if at least one of the line had `copy_action: rename`, we delete the original field after all lines have been processed.

**Comment by tonymeehan** [comment]
I agree with this. Default to copy is good, as I think changing the source data by removing fields should be an exception. Also good with renaming the flag to copy-action.

In the case where there are multiple source fields with rename actions, I like the idea of just aborting and throwing an error back to the user. For instance, what if 2 of the 3 source fields have rename action? Which one would we pick then?

**Comment by webmat** [comment]
Yeah that's what I meant with "then if at least one of the lines had rename"...

If there's no mention of renaming the field anywhere, it remains "copy". If there's at least one place where it's "rename", then we rename. But we do that only after processing each line that the user was processing that source_field, no matter the order.

I want this tool to be very forgiving of the stuff that can sneak into these brainstorming spreadsheets.

**Comment by tonymeehan** [comment]
Closing with https://github.com/elastic/ecs-mapper/pull/10.
